enum Message {
  SomeInvalidFields = "Some fields are invalid.",
  SomethingWrong = "Something went wrong. Please try again.",
  EmailExists = "Email already exists.",
  PhoneExists = "Phone number already exists.",
  UsernameExists = "Username already exists.",
  InvalidAccountType = "Please choose the account type.",
  AccountCreated = "Your account was created successfully.",
  AccountSetupSuccess = "Account setup successful. Please wait for approval.",
  TokenExpired = "Token is invalid or expired.",
  TokenIsMissing = "Token is missing.",
  OnboardingSuccessful = "Onboarding successful. Please verify your email and phone number.",
  UpdatePhoneSuccess = "Phone numbers were successfully updated.",
  InvalidCredentials = "Email or password is incorrect.",
  SendCodeSuccess = "Verification code sent successfully.",
  VerificationSuccess = "Two-factor verification successful.",
  InvalidEmailOTP = "Email OTP code is incorrect.",
  InvalidPhoneOTP = "Phone OTP code is incorrect.",
  TooCommonPassword = "Password is too common.",
  FileisTooLarge = "File is too large. Max size is 50MB.",
  FileTypeInvalid = "File type is invalid.",
  InvalidPassword = "Invalid credentials.",
  InvalidOTP = "Invalid OTP.",
  SetUpOtpSuccess = "OTP verified successfully.",
  AddMfaMethodSuccess = "MFA method added successfully.",
  EmailSent = "Verification code sent to your email successfully.",
  ContactSuccess = "Your message has been sent successfully.",
  IsUnderReview = "Your account is under review.",
  SecurityQuestionsUpdated = "Security questions updated successfully.",
}

export default Message;
